name: Deploy
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: mymindstorm/setup-emsdk@v7
        with:
          actions-cache-folder: "emsdk-cache"

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - run: sudo chmod -R 777 test/fixtures

      - name: Debug
        run: ls -la test/fixtures

      - run: npm ci
      - run: mkdir out && npm run compile

      - name: Test
        run: npm run test
        env:
          CI: true

      - name: Build webpack bundle
        run: npm run build
