name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - run: npm ci

      - name: Build webpack bundle
        run: npm run build

      - name: echo "ic-analyze.kaciras.com" > dist/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLEAN: true
          BRANCH: gh-pages
          FOLDER: dist
