name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - run: npm i -g pnpm

      - run: pnpm i --frozen-lockfile

      - name: Build webpack bundle
        run: pnpm run build

      - name: Enable custom domain
        run: echo "ic-analyze.kaciras.com" > dist/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          clean: true
          branch: gh-pages
          folder: dist
