name: Test
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - run: npm ci

      - name: Build webpack bundle
        run: npm run build

      - name: Test
        run: npm run test
        env:
          CI: true
