name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - run: npm ci

      - name: Build webpack bundle
        run: npm run build

      - name: Test
        run: npm run test
        env:
          CI: true
